# S3 Bucket for user uploads (documents, invoices, etc.)
resource "aws_s3_bucket" "uploads" {
  bucket        = "${var.project_name}-uploads-${var.environment}"
  force_destroy = false # Protect against accidental deletion of user data

  tags = {
    Name        = "${var.project_name}-uploads-${var.environment}"
    Environment = var.environment
  }
}

# Block ALL public access to the bucket
# Files will only be accessible via Presigned URLs generated by the Backend
resource "aws_s3_bucket_public_access_block" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# CORS Configuration for the bucket
# Crucial for allowing the frontend to upload files directly using the Presigned URL
resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "POST", "GET"]
    allowed_origins = ["*"] # In production, restrict this to your CloudFront domain
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}