export const WORLD_COUNTRIES = [
  { code: "AF", name: "Afganistán", flag: "🇦🇫", currency: "AFN" },
  { code: "AL", name: "Albania", flag: "🇦🇱", currency: "ALL" },
  { code: "DE", name: "Alemania", flag: "🇩🇪", currency: "EUR" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", currency: "EUR" },
  { code: "AO", name: "Angola", flag: "🇦🇴", currency: "AOA" },
  { code: "AI", name: "Anguila", flag: "🇦🇮", currency: "XCD" },
  { code: "AQ", name: "Antártida", flag: "🇦🇶", currency: "USD" },
  { code: "AG", name: "Antigua y Barbuda", flag: "🇦🇬", currency: "XCD" },
  { code: "SA", name: "Arabia Saudí", flag: "🇸🇦", currency: "SAR" },
  { code: "DZ", name: "Argelia", flag: "🇩🇿", currency: "DZD" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", currency: "ARS" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", currency: "AMD" },
  { code: "AW", name: "Aruba", flag: "🇦🇼", currency: "AWG" },
  { code: "AU", name: "Australia", flag: "🇦🇺", currency: "AUD" },
  { code: "AT", name: "Austria", flag: "🇦🇹", currency: "EUR" },
  { code: "AZ", name: "Azerbaiyán", flag: "🇦🇿", currency: "AZN" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", currency: "BSD" },
  { code: "BD", name: "Bangladés", flag: "🇧🇩", currency: "BDT" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", currency: "BBD" },
  { code: "BH", name: "Baréin", flag: "🇧🇭", currency: "BHD" },
  { code: "BE", name: "Bélgica", flag: "🇧🇪", currency: "EUR" },
  { code: "BZ", name: "Belice", flag: "🇧🇿", currency: "BZD" },
  { code: "BJ", name: "Benín", flag: "🇧🇯", currency: "XOF" },
  { code: "BM", name: "Bermudas", flag: "🇧🇲", currency: "BMD" },
  { code: "BY", name: "Bielorrusia", flag: "🇧🇾", currency: "BYN" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", currency: "BOB" },
  { code: "BA", name: "Bosnia y Herzegovina", flag: "🇧🇦", currency: "BAM" },
  { code: "BW", name: "Botsuana", flag: "🇧🇼", currency: "BWP" },
  { code: "BR", name: "Brasil", flag: "🇧🇷", currency: "BRL" },
  { code: "BN", name: "Brunéi", flag: "🇧🇳", currency: "BND" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", currency: "BGN" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", currency: "XOF" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", currency: "BIF" },
  { code: "BT", name: "Bután", flag: "🇧🇹", currency: "BTN" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", currency: "CVE" },
  { code: "KH", name: "Camboya", flag: "🇰🇭", currency: "KHR" },
  { code: "CM", name: "Camerún", flag: "🇨🇲", currency: "XAF" },
  { code: "CA", name: "Canadá", flag: "🇨🇦", currency: "CAD" },
  { code: "QA", name: "Catar", flag: "🇶🇦", currency: "QAR" },
  { code: "TD", name: "Chad", flag: "🇹🇩", currency: "XAF" },
  { code: "CL", name: "Chile", flag: "🇨🇱", currency: "CLP" },
  { code: "CN", name: "China", flag: "🇨🇳", currency: "CNY" },
  { code: "CY", name: "Chipre", flag: "🇨🇾", currency: "EUR" },
  { code: "VA", name: "Ciudad del Vaticano", flag: "🇻🇦", currency: "EUR" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", currency: "COP" },
  { code: "KM", name: "Comoras", flag: "🇰🇲", currency: "KMF" },
  { code: "KP", name: "Corea del Norte", flag: "🇰🇵", currency: "KPW" },
  { code: "KR", name: "Corea del Sur", flag: "🇰🇷", currency: "KRW" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", currency: "CRC" },
  { code: "CI", name: "Costa de Marfil", flag: "🇨🇮", currency: "XOF" },
  { code: "HR", name: "Croacia", flag: "🇭🇷", currency: "EUR" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", currency: "CUP" },
  { code: "CW", name: "Curazao", flag: "🇨🇼", currency: "ANG" },
  { code: "DK", name: "Dinamarca", flag: "🇩🇰", currency: "DKK" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", currency: "XCD" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", currency: "USD" },
  { code: "EG", name: "Egipto", flag: "🇪🇬", currency: "EGP" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", currency: "USD" },
  { code: "AE", name: "Emiratos Árabes Unidos", flag: "🇦🇪", currency: "AED" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", currency: "ERN" },
  { code: "SK", name: "Eslovaquia", flag: "🇸🇰", currency: "EUR" },
  { code: "SI", name: "Eslovenia", flag: "🇸🇮", currency: "EUR" },
  { code: "ES", name: "España", flag: "🇪🇸", currency: "EUR" },
  { code: "US", name: "Estados Unidos", flag: "🇺🇸", currency: "USD" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", currency: "EUR" },
  { code: "SZ", name: "Esuatini", flag: "🇸🇿", currency: "SZL" },
  { code: "ET", name: "Etiopía", flag: "🇪🇹", currency: "ETB" },
  { code: "PH", name: "Filipinas", flag: "🇵🇭", currency: "PHP" },
  { code: "FI", name: "Finlandia", flag: "🇫🇮", currency: "EUR" },
  { code: "FJ", name: "Fiyi", flag: "🇫🇯", currency: "FJD" },
  { code: "FR", name: "Francia", flag: "🇫🇷", currency: "EUR" },
  { code: "GA", name: "Gabón", flag: "🇬🇦", currency: "XAF" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", currency: "GMD" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", currency: "GEL" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", currency: "GHS" },
  { code: "GI", name: "Gibraltar", flag: "🇬🇮", currency: "GIP" },
  { code: "GD", name: "Granada", flag: "🇬🇩", currency: "XCD" },
  { code: "GR", name: "Grecia", flag: "🇬🇷", currency: "EUR" },
  { code: "GL", name: "Groenlandia", flag: "🇬🇱", currency: "DKK" },
  { code: "GP", name: "Guadalupe", flag: "🇬🇵", currency: "EUR" },
  { code: "GU", name: "Guam", flag: "🇬🇺", currency: "USD" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", currency: "GTQ" },
  { code: "GF", name: "Guayana Francesa", flag: "🇬🇫", currency: "EUR" },
  { code: "GG", name: "Guernsey", flag: "🇬🇬", currency: "GBP" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", currency: "GNF" },
  { code: "GQ", name: "Guinea Ecuatorial", flag: "🇬🇶", currency: "XAF" },
  { code: "GW", name: "Guinea-Bisáu", flag: "🇬🇼", currency: "XOF" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", currency: "GYD" },
  { code: "HT", name: "Haití", flag: "🇭🇹", currency: "HTG" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", currency: "HNL" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", currency: "HKD" },
  { code: "HU", name: "Hungría", flag: "🇭🇺", currency: "HUF" },
  { code: "IN", name: "India", flag: "🇮🇳", currency: "INR" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", currency: "IDR" },
  { code: "IQ", name: "Irak", flag: "🇮🇶", currency: "IQD" },
  { code: "IR", name: "Irán", flag: "🇮🇷", currency: "IRR" },
  { code: "IE", name: "Irlanda", flag: "🇮🇪", currency: "EUR" },
  { code: "BV", name: "Isla Bouvet", flag: "🇧🇻", currency: "NOK" },
  { code: "IM", name: "Isla de Man", flag: "🇮🇲", currency: "GBP" },
  { code: "CX", name: "Isla de Navidad", flag: "🇨🇽", currency: "AUD" },
  { code: "IS", name: "Islandia", flag: "🇮🇸", currency: "ISK" },
  { code: "KY", name: "Islas Caimán", flag: "🇰🇾", currency: "KYD" },
  { code: "CC", name: "Islas Cocos", flag: "🇨🇨", currency: "AUD" },
  { code: "CK", name: "Islas Cook", flag: "🇨🇰", currency: "NZD" },
  { code: "FO", name: "Islas Feroe", flag: "🇫🇴", currency: "DKK" },
  { code: "FK", name: "Islas Malvinas", flag: "🇫🇰", currency: "FKP" },
  { code: "MP", name: "Islas Marianas del Norte", flag: "🇲🇵", currency: "USD" },
  { code: "MH", name: "Islas Marshall", flag: "🇲🇭", currency: "USD" },
  { code: "SB", name: "Islas Salomón", flag: "🇸🇧", currency: "SBD" },
  { code: "TC", name: "Islas Turcas y Caicos", flag: "🇹🇨", currency: "USD" },
  { code: "VG", name: "Islas Vírgenes Británicas", flag: "🇻🇬", currency: "USD" },
  { code: "VI", name: "Islas Vírgenes de EE. UU.", flag: "🇻🇮", currency: "USD" },
  { code: "IL", name: "Israel", flag: "🇮🇱", currency: "ILS" },
  { code: "IT", name: "Italia", flag: "🇮🇹", currency: "EUR" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", currency: "JMD" },
  { code: "JP", name: "Japón", flag: "🇯🇵", currency: "JPY" },
  { code: "JE", name: "Jersey", flag: "🇯🇪", currency: "GBP" },
  { code: "JO", name: "Jordania", flag: "🇯🇴", currency: "JOD" },
  { code: "KZ", name: "Kazajistán", flag: "🇰🇿", currency: "KZT" },
  { code: "KE", name: "Kenia", flag: "🇰🇪", currency: "KES" },
  { code: "KG", name: "Kirguistán", flag: "🇰🇬", currency: "KGS" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", currency: "AUD" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", currency: "KWD" },
  { code: "LA", name: "Laos", flag: "🇱🇦", currency: "LAK" },
  { code: "LS", name: "Lesoto", flag: "🇱🇸", currency: "LSL" },
  { code: "LV", name: "Letonia", flag: "🇱🇻", currency: "EUR" },
  { code: "LB", name: "Líbano", flag: "🇱🇧", currency: "LBP" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", currency: "LRD" },
  { code: "LY", name: "Libia", flag: "🇱🇾", currency: "LYD" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", currency: "CHF" },
  { code: "LT", name: "Lituania", flag: "🇱🇹", currency: "EUR" },
  { code: "LU", name: "Luxemburgo", flag: "🇱🇺", currency: "EUR" },
  { code: "MO", name: "Macao", flag: "🇲🇴", currency: "MOP" },
  { code: "MK", name: "Macedonia del Norte", flag: "🇲🇰", currency: "MKD" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", currency: "MGA" },
  { code: "MY", name: "Malasia", flag: "🇲🇾", currency: "MYR" },
  { code: "MW", name: "Malaui", flag: "🇲🇼", currency: "MWK" },
  { code: "MV", name: "Maldivas", flag: "🇲🇻", currency: "MVR" },
  { code: "ML", name: "Malí", flag: "🇲🇱", currency: "XOF" },
  { code: "MT", name: "Malta", flag: "🇲🇹", currency: "EUR" },
  { code: "MA", name: "Marruecos", flag: "🇲🇦", currency: "MAD" },
  { code: "MQ", name: "Martinica", flag: "🇲🇶", currency: "EUR" },
  { code: "MU", name: "Mauricio", flag: "🇲🇺", currency: "MUR" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", currency: "MRU" },
  { code: "YT", name: "Mayotte", flag: "🇾🇹", currency: "EUR" },
  { code: "MX", name: "México", flag: "🇲🇽", currency: "MXN" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", currency: "USD" },
  { code: "MD", name: "Moldavia", flag: "🇲🇩", currency: "MDL" },
  { code: "MC", name: "Mónaco", flag: "🇲🇨", currency: "EUR" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", currency: "MNT" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", currency: "EUR" },
  { code: "MS", name: "Montserrat", flag: "🇲🇸", currency: "XCD" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", currency: "MZN" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", currency: "MMK" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", currency: "NAD" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", currency: "AUD" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", currency: "NPR" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", currency: "NIO" },
  { code: "NE", name: "Níger", flag: "🇳🇪", currency: "XOF" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", currency: "NGN" },
  { code: "NU", name: "Niue", flag: "🇳🇺", currency: "NZD" },
  { code: "NO", name: "Noruega", flag: "🇳🇴", currency: "NOK" },
  { code: "NC", name: "Nueva Caledonia", flag: "🇳🇨", currency: "XPF" },
  { code: "NZ", name: "Nueva Zelanda", flag: "🇳🇿", currency: "NZD" },
  { code: "OM", name: "Omán", flag: "🇴🇲", currency: "OMR" },
  { code: "NL", name: "Países Bajos", flag: "🇳🇱", currency: "EUR" },
  { code: "PK", name: "Pakistán", flag: "🇵🇰", currency: "PKR" },
  { code: "PW", name: "Palaos", flag: "🇵🇼", currency: "USD" },
  { code: "PA", name: "Panamá", flag: "🇵🇦", currency: "PAB" },
  { code: "PG", name: "Papúa Nueva Guinea", flag: "🇵🇬", currency: "PGK" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", currency: "PYG" },
  { code: "PE", name: "Perú", flag: "🇵🇪", currency: "PEN" },
  { code: "PF", name: "Polinesia Francesa", flag: "🇵🇫", currency: "XPF" },
  { code: "PL", name: "Polonia", flag: "🇵🇱", currency: "PLN" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", currency: "EUR" },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷", currency: "USD" },
  { code: "GB", name: "Reino Unido", flag: "🇬🇧", currency: "GBP" },
  { code: "CF", name: "República Centroafricana", flag: "🇨🇫", currency: "XAF" },
  { code: "CZ", name: "República Checa", flag: "🇨🇿", currency: "CZK" },
  { code: "CG", name: "República del Congo", flag: "🇨🇬", currency: "XAF" },
  { code: "CD", name: "República Democrática del Congo", flag: "🇨🇩", currency: "CDF" },
  { code: "DO", name: "República Dominicana", flag: "🇩🇴", currency: "DOP" },
  { code: "RE", name: "Reunión", flag: "🇷🇪", currency: "EUR" },
  { code: "RW", name: "Ruanda", flag: "🇷🇼", currency: "RWF" },
  { code: "RO", name: "Rumania", flag: "🇷🇴", currency: "RON" },
  { code: "RU", name: "Rusia", flag: "🇷🇺", currency: "RUB" },
  { code: "EH", name: "Sahara Occidental", flag: "🇪🇭", currency: "MAD" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", currency: "WST" },
  { code: "AS", name: "Samoa Americana", flag: "🇦🇸", currency: "USD" },
  { code: "BL", name: "San Bartolomé", flag: "🇧🇱", currency: "EUR" },
  { code: "KN", name: "San Cristóbal y Nieves", flag: "🇰🇳", currency: "XCD" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", currency: "EUR" },
  { code: "MF", name: "San Martín", flag: "🇲🇫", currency: "EUR" },
  { code: "PM", name: "San Pedro y Miquelón", flag: "🇵🇲", currency: "EUR" },
  { code: "VC", name: "San Vicente y las Granadinas", flag: "🇻🇨", currency: "XCD" },
  { code: "SH", name: "Santa Elena", flag: "🇸🇭", currency: "SHP" },
  { code: "LC", name: "Santa Lucía", flag: "🇱🇨", currency: "XCD" },
  { code: "ST", name: "Santo Tomé y Príncipe", flag: "🇸🇹", currency: "STN" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", currency: "XOF" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", currency: "RSD" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", currency: "SCR" },
  { code: "SL", name: "Sierra Leona", flag: "🇸🇱", currency: "SLL" },
  { code: "SG", name: "Singapur", flag: "🇸🇬", currency: "SGD" },
  { code: "SX", name: "Sint Maarten", flag: "🇸🇽", currency: "ANG" },
  { code: "SY", name: "Siria", flag: "🇸🇾", currency: "SYP" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", currency: "SOS" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", currency: "LKR" },
  { code: "ZA", name: "Sudáfrica", flag: "🇿🇦", currency: "ZAR" },
  { code: "SD", name: "Sudán", flag: "🇸🇩", currency: "SDG" },
  { code: "SS", name: "Sudán del Sur", flag: "🇸🇸", currency: "SSP" },
  { code: "SE", name: "Suecia", flag: "🇸🇪", currency: "SEK" },
  { code: "CH", name: "Suiza", flag: "🇨🇭", currency: "CHF" },
  { code: "SR", name: "Surinam", flag: "🇸🇷", currency: "SRD" },
  { code: "SJ", name: "Svalbard y Jan Mayen", flag: "🇸🇯", currency: "NOK" },
  { code: "TH", name: "Tailandia", flag: "🇹🇭", currency: "THB" },
  { code: "TW", name: "Taiwán", flag: "🇹🇼", currency: "TWD" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", currency: "TZS" },
  { code: "TJ", name: "Tayikistán", flag: "🇹🇯", currency: "TJS" },
  { code: "IO", name: "Territorio Británico del Océano Índico", flag: "🇮🇴", currency: "USD" },
  { code: "TF", name: "Territorios Australes Franceses", flag: "🇹🇫", currency: "EUR" },
  { code: "PS", name: "Territorios Palestinos", flag: "🇵🇸", currency: "ILS" },
  { code: "TL", name: "Timor Oriental", flag: "🇹🇱", currency: "USD" },
  { code: "TG", name: "Togo", flag: "🇹🇬", currency: "XOF" },
  { code: "TK", name: "Tokelau", flag: "🇹🇰", currency: "NZD" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", currency: "TOP" },
  { code: "TT", name: "Trinidad y Tobago", flag: "🇹🇹", currency: "TTD" },
  { code: "TN", name: "Túnez", flag: "🇹🇳", currency: "TND" },
  { code: "TM", name: "Turkmenistán", flag: "🇹🇲", currency: "TMT" },
  { code: "TR", name: "Turquía", flag: "🇹🇷", currency: "TRY" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", currency: "AUD" },
  { code: "UA", name: "Ucrania", flag: "🇺🇦", currency: "UAH" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", currency: "UGX" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", currency: "UYU" },
  { code: "UZ", name: "Uzbekistán", flag: "🇺🇿", currency: "UZS" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", currency: "VUV" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", currency: "VES" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", currency: "VND" },
  { code: "WF", name: "Wallis y Futuna", flag: "🇼🇫", currency: "XPF" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", currency: "YER" },
  { code: "DJ", name: "Yibuti", flag: "🇩🇯", currency: "DJF" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", currency: "ZMW" },
  { code: "ZW", name: "Zimbabue", flag: "🇿🇼", currency: "ZWL" },
  { code: "OTHER", name: "Otro", flag: "🌎", currency: "USD" }
];

// Generar WORLD_CURRENCIES dinámicamente o con lista manual
const currencyNames: Record<string, string> = {
  AED: "Dírham de los Emiratos Árabes Unidos", AFN: "Afgani afgano", ALL: "Lek albanés", AMD: "Dram armenio",
  ANG: "Florín antillano neerlandés", AOA: "Kwanza angoleño", ARS: "Peso argentino", AUD: "Dólar australiano",
  AWG: "Florín arubeño", AZN: "Manat azerbaiyano", BAM: "Marco convertible", BBD: "Dólar barbadense",
  BDT: "Taka bangladesí", BGN: "Lev búlgaro", BHD: "Dinar bareiní", BIF: "Franco burundés",
  BMD: "Dólar bermudeño", BND: "Dólar bruneano", BOB: "Boliviano", BRL: "Real brasileño",
  BSD: "Dólar bahameño", BTN: "Ngultrum butanés", BWP: "Pula botsuano", BYN: "Rublo bielorruso",
  BZD: "Dólar beliceño", CAD: "Dólar canadiense", CDF: "Franco congoleño", CHF: "Franco suizo",
  CLP: "Peso chileno", CNY: "Yuan chino", COP: "Peso colombiano", CRC: "Colón costarricense",
  CUP: "Peso cubano", CVE: "Escudo caboverdiano", CZK: "Corona checa", DJF: "Franco yibutiano",
  DKK: "Corona danesa", DOP: "Peso dominicano", DZD: "Dinar argelino", EGP: "Libra egipcia",
  ERN: "Nakfa eritreo", ETB: "Birr etíope", EUR: "Euro", FJD: "Dólar fiyiano",
  FKP: "Libra malvinense", GBP: "Libra esterlina", GEL: "Lari georgiano", GHS: "Cedi ghanés",
  GIP: "Libra gibraltareña", GMD: "Dalasi gambiano", GNF: "Franco guineano", GTQ: "Quetzal guatemalteco",
  GYD: "Dólar guyanés", HKD: "Dólar de Hong Kong", HNL: "Lempira hondureño", HTG: "Gourde haitiano",
  HUF: "Forinto húngaro", IDR: "Rupia indonesia", ILS: "Nuevo séquel israelí", INR: "Rupia india",
  IQD: "Dinar iraquí", IRR: "Rial iraní", ISK: "Corona islandesa", JMD: "Dólar jamaicano",
  JOD: "Dinar jordano", JPY: "Yen japonés", KES: "Chelín keniano", KGS: "Som kirguís",
  KHR: "Riel camboyano", KMF: "Franco comorense", KPW: "Won norcoreano", KRW: "Won surcoreano",
  KWD: "Dinar kuwaití", KYD: "Dólar de las Islas Caimán", KZT: "Tenge kazajo", LAK: "Kip laosiano",
  LBP: "Libra libanesa", LKR: "Rupia de Sri Lanka", LRD: "Dólar liberiano", LSL: "Loti lesotense",
  LYD: "Dinar libio", MAD: "Dírham marroquí", MDL: "Leu moldavo", MGA: "Ariary malgache",
  MKD: "Dinar macedonio", MMK: "Kyat birmano", MNT: "Tugrik mongol", MOP: "Pataca macanesa",
  MRU: "Uguiya mauritano", MUR: "Rupia de Mauricio", MVR: "Rupia maldiva", MWK: "Kwacha malauí",
  MXN: "Peso mexicano", MYR: "Ringgit malayo", MZN: "Metical mozambiqueño", NAD: "Dólar namibio",
  NGN: "Naira nigeriano", NIO: "Córdoba nicaragüense", NOK: "Corona noruega", NPR: "Rupia nepalí",
  NZD: "Dólar neozelandés", OMR: "Rial omaní", PAB: "Balboa panameño", PEN: "Sol peruano",
  PGK: "Kina papú", PHP: "Peso filipino", PKR: "Rupia pakistaní", PLN: "Zloty polaco",
  PYG: "Guaraní paraguayo", QAR: "Riyal catarí", RON: "Leu rumano", RSD: "Dinar serbio",
  RUB: "Rublo ruso", RWF: "Franco ruandés", SAR: "Riyal saudí", SBD: "Dólar de las Islas Salomón",
  SCR: "Rupia seychellense", SDG: "Libra sudanesa", SEK: "Corona sueca", SGD: "Dólar singapurense",
  SHP: "Libra de Santa Elena", SLL: "Leone sierraleonés", SOS: "Chelín somalí", SRD: "Dólar surinamés",
  SSP: "Libra sursudanesa", STN: "Dobra santotomense", SYP: "Libra siria", SZL: "Lilangeni suazi",
  THB: "Baht tailandés", TJS: "Somoni tayiko", TMT: "Manat turcomano", TND: "Dinar tunecino",
  TOP: "Paʻanga tongano", TRY: "Lira turca", TTD: "Dólar de Trinidad y Tobago", TWD: "Nuevo dólar taiwanés",
  TZS: "Chelín tanzano", UAH: "Grivna ucraniana", UGX: "Chelín ugandés", USD: "Dólar estadounidense",
  UYU: "Peso uruguayo", UZS: "Som uzbeko", VES: "Bolívar soberano", VND: "Dong vietnamita",
  VUV: "Vatu vanuatuense", WST: "Tala samoano", XAF: "Franco CFA de África Central", XCD: "Dólar del Caribe Oriental",
  XOF: "Franco CFA de África Occidental", XPF: "Franco CFP", YER: "Rial yemení", ZAR: "Rand sudafricano",
  ZMW: "Kwacha zambiano", ZWL: "Dólar zimbabuense"
};

// Generar array deduplicado y ordenado a partir del diccionario
export const WORLD_CURRENCIES = Object.keys(currencyNames).map(code => ({
  code,
  name: currencyNames[code]
})).sort((a, b) => a.code.localeCompare(b.code));
